[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "r8scli"
description = "Rightsizer CLI"
requires-python = ">=3.14,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "click>=8.3,<9",
    "prettytable>=3.9,<4",
    "python-dateutil>=2.9,<3",
    "modular-cli-sdk[hvac]>=3.1.5,<4",
    "requests>=2.31,<3"
]

[project.scripts]
r8s = "r8scli.group.r8s:r8s"

[tool.setuptools.dynamic]
version = {attr = "r8scli.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["r8scli*"]
namespaces = false

[tool.pyright]
include = ["r8scli"]
exclude = [
    "**/__pycache__",
]
pythonVersion = "3.14"
reportIncompatibleMethodOverride = "warning"
