apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rightsizer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rightsizer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rightsizer.chart" . }}
data:
  inner-cache-ttl-seconds: {{ .Values.innerCacheTTLSeconds | quote }}
  db-name: {{ .Values.databaseName }}
  modular-db-name: {{ .Values.modularDatabaseName }}