apiVersion: v1
kind: Service
metadata:
  name: {{ include "rightsizer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rightsizer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rightsizer.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "rightsizer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      targetPort: http
      port: {{ .Values.service.port }}
      {{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
