FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /r8s

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY src/requirements.txt src/requirements.txt
COPY docker/requirements.txt docker/requirements.txt
COPY src/exported_module/requirements.txt src/exported_module/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r src/requirements.txt \
    && pip install --no-cache-dir -r docker/requirements.txt \
    && pip install --no-cache-dir -r src/exported_module/requirements.txt

RUN python3 -m venv /r8s/docker/.executor_venv && \
    /r8s/docker/.executor_venv/bin/pip install --no-cache-dir -r docker/requirements.txt

COPY src src
COPY docker docker
COPY scripts scripts

ENV APP_ENV=production
ENV APP_PORT=8000

EXPOSE 8000

CMD sh -c "python src/exported_module/scripts/init.py && python src/exported_module/scripts/init_customer.py -name DEMO && python scripts/populate_aws_shapes_from_file.py && python scripts/populate_demo_config.py && python scripts/populate_demo_metrics.py && python src/main.py"
