apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defectdojo.fullname" . }}-cache
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
  volumeName: {{ include "defectdojo.fullname" . }}-cache
  accessModes:
    - {{ .Values.persistence.cacheVolume.accessMode }}
  storageClassName: {{ .Values.persistence.cacheVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.cacheVolume.size }}
