apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "defectdojo.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.dataVolume.size }}
  accessModes:
    - {{ .Values.persistence.dataVolume.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.dataVolume.storageClass }}
  hostPath:
    path: {{ .Values.persistence.dataVolume.hostPath }}
