apiVersion: v1
kind: Service
metadata:
  name: {{ include "defectdojo.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      protocol: TCP
      port: 5432
      targetPort: 5432
