apiVersion: v1
kind: Service
metadata:
  name: uwsgi  # todo cannot be changed currently because hardcoded inside nginx image
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}-uwsgi
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      protocol: TCP
      port: 3031
      targetPort: 3031
